# THIS IS AN EXAMPLE CURRENT MEMBER
#
#- alias: meren
#  official: True
#  name: A. Murat Eren (Meren)
#  tenure_start: 10/2015
#  role: PI
#  twitter: merenbey
#  github: meren
#  web: http://meren.org
#  avatar: bio-meren.jpg
#  email: a.murat.eren@gmail.com
#  linkedin: meren
#  orcid: 0000-0001-9013-4827
#  phone: +1-773-702-5935
#  fax: +1-773-702-2281
#  skype: a.murat.eren
#  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9118, Chicago, IL 60637 USA
#  bio: "I am a computer scientist with a deep appreciation for the complexity of life. I design algorithms and experiments to better understand microbes and their ecology."
#  affiliations:
#    - title: MBL Fellow
#      inst: Marine Biological Laboratory
#      inst_link: http://www.mbl.edu/research/mbl-fellows/a-murat-eren/
#    - title: Assistant Professor
#      inst: The Department of Medicine at the University of Chicago
#      inst_link: http://medicine.uchicago.edu/
#    - title: Committee on Microbiology
#      inst: The Biomedical Sciences Cluster at the University of Chicago
#      inst_link: https://biomedsciences.uchicago.edu/
#
#
# THIS IS AN EXAMPLE PAST MEMBER:
#
#- alias: alon
#  nick_name: Alon
#  tenure_start: 10/2016
#  tenure_end: 02/2020
#  current_info: a Genomics Data Scientist at <a href="https://weill.cornell.edu/">Weill Cornell Medicine</a>
#  contributions: Throughout his studies of the human oral cavity microbiome and its enigmatic members via genome-resolved metagenomics, he served the community with his open code and tutorials. Alon, <a href="https://twitter.com/merenbey/status/1223038960789872646" target="_blank">the very first graduate student to join our group</a>, dramatically influenced the trajectory of our science
#  official: True
#  name: Alon Shaiber
#  role: Graduate Student
#  email: alon.shaiber@gmail.com
#  twitter: alon_shaiber
#  orcid: 0000-0002-4806-9280
#  github: ShaiberAlon
#  linkedin: alon-shaiber
#  skype: alon.shaiber
#  avatar: bio-alon.jpg
#  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
#  bio: "I'm a graduate student in the Bio Physical Sciences Program at UChicago. I'm fascinated by the complexity of microbial ecology and interested in applying and developing computational tools to explore it."
#  affiliations:
#    - title: Graduate Student
#      inst: The Biophysical Sciences Program at the University of Chicago
#      inst_link: http://biophysics.uchicago.edu/

- alias: bana
  official: True
  name: Bana Jabri
  tenure_start: 01/2000
  role: PI
  web: https://immunology.uchicago.edu/program/faculty/bana-jabri
  avatar: bio-jabri.jpg
  email: bjabri@uchicago.edu
  twitter: BanaJabri
  orcid: 0000-0001-7427-4424
  web:
  linkedin:
  github:
  youtube:
  phone: +1-773-702-5935
  fax: +1-773-702-2281
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9116, Chicago, IL 60637 USA
  bio: "I am an immunologist."
  affiliations:
    - title: Professor
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/
    - title: Committee on Immunology
      inst: The Biomedical Sciences Cluster at the University of Chicago
      inst_link: https://immunology.uchicago.edu/
      inst: The Biomedical Sciences Cluster at the University of Chicago
      inst_link: https://metabolism.uchicago.edu/


- alias: fillman
  official: True
  name: Natalie Fillman
  tenure_start: 01/2000
  role: Clinic Coordinator
  email:
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin: https://www.linkedin.com/in/natalie-fillman-md-56516091
  github:
  youtube:
  avatar: bio-fillman.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am a medical graduate interested in clinical research in Inflammatory bowel disease. Focusing on a clinical study in Crohn’s disease."
  affiliations:
    - title: Clinic Coordinator
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: Borregard
  official: True
  name: Megan Hoinville
  tenure_start: 01/2000
  role: PhD student in Biophysical Sciences
  email: mehoinville@uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-borregard.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "Research Statement: I am interested in studying the regulation of effector function in human tissue resident memory T cells."
  affiliations:
    - title: PhD student in Biophysical Sciences
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: sangani
  official: True
  name: Kishan Sangani
  tenure_start: 01/2000
  role: MSTP Student
  email: ksangani@uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-sangani.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am interested in understanding the consequences of age-associated somatic mutations in the hematopoietic system. I use murine models and patient samples to study how host-microbe interactions may impact progression towards malignant states secondary to these somatic mutations."
  affiliations:
    - title: MSTP Student
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: mayassi
  official: True
  name: Toufic Mayassi
  tenure_start: 01/2000
  role: Broad Institute of MIT and Harvard // Past COI student and postdoc in her lab
  email:
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-mayassi.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am interested in using systems approaches to answer basic immunology questions in the human setting. More specifically, I am working on better understanding tissue-resident immune responses using celiac disease as a model."
  affiliations:
    - title: Broad Institute of MIT and Harvard // Past COI student and postdoc in her lab
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: dinardi
  official: True
  name: Nick DiNardi
  tenure_start: 01/2000
  role: Post-doctoral Scientist
  email:
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-blank-male.png
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am a graduate student interested in combining basic science and clinical research to answer questions on Inflammatory Bowel Disease and Celiac’s Disease in applicable ways."
  affiliations:
    - title: Post-doctoral Scientist
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: malik
  official: True
  name: Ankit Malik
  tenure_start: 01/2000
  role: Post-doctoral Scientist
  email: malikank@uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-malik.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "Intestinal epithelial cells are not only the targets for destruction during autoimmunity but are immunologically active and can orchestrate immune responses. I am studying how epithelial cells react to pathogens, commensals and environmental agents, and how that affects local and distal immunes responses."
  affiliations:
    - title: Post-doctoral Scientist
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: franzen
  official: True
  name: Carrie Franzen
  tenure_start: 01/2000
  role: Lab manager
  email: cfranzen@bsd.uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-franzen.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am interested in understanding the pathogenesis and predicting treatment response in patients with inflammatory bowel disease using multi-parametric flow cytometry."
  affiliations:
    - title: Lab manager
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: fuessel
  official: True
  name: Jessika Fuessel
  tenure_start: 01/2000
  role: Research Professional
  email: ju.fuessel@uchicago.edu
  twitter:
  orcid: 0000-0002-4210-2318
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-fuessel.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "My aim is to understand the fate and impact of microbial metabolites within the host organisms. I am especially interested in the relationship of inflammatory bowel disease and the nature of microbially metabolites produced in the small intestine."
  affiliations:
    - title: Research Professional
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: sharma
  official: True
  name: Deepika Sharma
  tenure_start: 01/2000
  role: Post-doctoral Scientist
  email: sharmad@uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-sharma.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am interested in the concept of “immune- dictation”, processes such as priming, polarization and tolerance that mold the inflammatory response during homeostatic and inflammatory processes. How these processes are engaged within the gut mucosa to set the immune-tone, and impact both local and distal inflammation form the foundation for my research."
  affiliations:
    - title: Post-doctoral Scientist
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: voisine
  official: True
  name: Jordan Voisine
  tenure_start: 01/2000
  role: COI PhD Student
  email: jvoisine@uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-voisine.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "My research interests lie in uncovering the molecular mechanisms that lead to and drive autoimmunity. I am currently studying the pathogenesis of Celiac Disease, an autoimmune-like disorder of the small intestine."
  affiliations:
    - title: COI PhD Student
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: discepolo
  official: True
  name: Valentina Discepolo
  tenure_start: 01/2000
  role: Post-doctoral Scientist (??)
  email:
  linkedin: valentina-discepolo
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-discepolo.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am a physician scientist with an expertise in gastroenterology and mucosal immunology. Understanding the origin of autoimmune processes is my main interest. My work in Bana's lab aims at dissecting the interplay between environmental and genetic factors in triggering inflammatory responses in the context of celiac disease. Ultimately, this will help designing new personalized preventive and therapeutic strategies for patients at risk to develop autoimmune disorders."
  affiliations:
    - title: Post-doctoral Scientist (??)
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: stromberg
  official: True
  name: Ariel Halper Stromberg
  tenure_start: 01/2000
  role: GI Fellow
  email: ahalperstromberg@medicine.bsd.uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-stromberg.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "The causes of inflammatory bowel disease (IBD) remain incompletely understood, but environment factors, host genetics, and the immune system are known to play important roles. My work investigates the underlying immune pathways that drive IBD pathogenesis with a goal of exploiting these pathways to develop new diagnostic tools and therapies."
  affiliations:
    - title: GI Fellow
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/


- alias: earley
  official: True
  name: Zachary M Earley
  tenure_start: 01/2000
  role: Post-doctoral Scientist // past COI PhD Student
  email: zearley@uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-earley.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am interested in studying host microbe interactions in the context of homeostasis and inflammation"
  affiliations:
    - title: Post-doctoral Scientist // past COI PhD Student
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: lisicka
  official: True
  name: Wioletta Lisicka
  tenure_start: 01/2000
  role: COI PhD Student
  email: wlisicka@uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-blank-female.png
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am interested in Host-microbe interactions in autoimmune diseases"
  affiliations:
    - title: COI PhD Student
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

####################################################################################
# Previous members.
####################################################################################

- alias: wang
  official: True
  name: Anni Wang
  tenure_start: 01/2000
  tenure_end: 01/2000
  current_info: 
  role: Lab Technician // Alumni
  email: anniw@uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-wang.jpeg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I don't have a research statement."
  affiliations:
    - title: Lab Technician // Alumni
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: Ciszewski
  official: True
  name: Cezary Ciszewski
  tenure_start: 01/2000
  tenure_end: 01/2000
  current_info: 
  role: Lab Manager
  email: cciszews@bsd.uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  phone: +1-773-824-6927
  avatar: bio-Cez.jpeg
  address: Human Disease & Immune Discovery Core Facility, University of Chicago, 900 E 57th Street, KCBD, Room #1260A, Chicago IL 60637
  bio: "I don't have a research statement."
  affiliations:
    - title: Lab Manager
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: ernest
  official: True
  name: Jordan Ernest
  tenure_start: 01/2000
  tenure_end: 01/2000
  role: Lab Technician
  email: jernest1@medicine.bsd.uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-ernest.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am interested in ways that the immune system supports tissue function and homeostasis outside of eliminating pathogens, such as the role it plays in regulating metabolic homeostasis, thermogenesis, and tissue repair."
  affiliations:
    - title: Lab Technician
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: shaw
  official: True
  name: Dustin Shaw
  tenure_start: 01/2000
  tenure_end: 01/2000
  role: MSTP Student
  email: dgshaw@uchicago.edu
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-shaw.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am interested in the differences in the inflammation observed in inflammatory bowel disease and primary sclerosing cholangitis, specifically as it relates to the development of colorectal cancer. We are taking a multi-“omics” approach, which includes transcriptomics, metagenomics, flow cytometry, and other assays."
  affiliations:
    - title: MSTP Student
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: kowalczyk
  official: True
  name: Anita Kowalczyk
  tenure_start: 01/2000
  tenure_end: 01/2000
  role: Post-doctoral Scientist (??)
  email:
  twitter:
  orcid: 0000-0000-0000-0000
  web:
  linkedin:
  github:
  youtube:
  avatar: bio-kowalczyk.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, Chicago, IL 60637 USA
  bio: "I am interested in how translocation of gut resident bacteria impacts mucosal immunity. I’m also studying the contribution of immunoglobulin A to shaping the intestinal immune response."
  affiliations:
    - title: Post-doctoral Scientist (??)
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/
